// Comprehensive Directory of Earth Nations & Universal Realms
// Used for Global Search Autocomplete and Constellation Teleportation

export interface EarthRegion {
  name: string;
  flag: string;
  category: "nation" | "realm" | "city";
  keywords?: string[];
}

export const WORLD_REGIONS: EarthRegion[] = [
  // Iconic Metropolitan Centers
  { name: "New York, USA", flag: "🗽", category: "city", keywords: ["nyc", "united states", "manhattan", "america"] },
  { name: "San Francisco, USA", flag: "🌉", category: "city", keywords: ["california", "silicon valley", "bay area"] },
  { name: "Seattle, USA", flag: "🌲", category: "city", keywords: ["washington", "pacific northwest", "rain"] },
  { name: "Austin, USA", flag: "🎸", category: "city", keywords: ["texas", "atx", "live music"] },
  { name: "Chicago, USA", flag: "🏙️", category: "city", keywords: ["illinois", "windy city", "midwest"] },
  { name: "Boston, USA", flag: "⛵", category: "city", keywords: ["massachusetts", "new england", "harvard"] },
  { name: "Los Angeles, USA", flag: "🌴", category: "city", keywords: ["california", "hollywood", "america"] },
  { name: "Miami, USA", flag: "🏝️", category: "city", keywords: ["florida", "south beach", "atlantic"] },
  { name: "London, United Kingdom", flag: "🇬🇧", category: "city", keywords: ["uk", "england", "britain"] },
  { name: "Tokyo, Japan", flag: "🇯🇵", category: "city", keywords: ["japan", "shibuya", "asia"] },
  { name: "Paris, France", flag: "🇫🇷", category: "city", keywords: ["france", "europe", "eiffel"] },
  { name: "Toronto, Canada", flag: "🇨🇦", category: "city", keywords: ["canada", "ontario"] },
  { name: "Sydney, Australia", flag: "🇦🇺", category: "city", keywords: ["australia", "nsw", "oceania"] },
  { name: "Berlin, Germany", flag: "🇩🇪", category: "city", keywords: ["germany", "europe"] },

  // Special Poetic Realms
  { name: "Pacific Ocean (High Seas)", flag: "🌊", category: "realm", keywords: ["ocean", "sea", "ship", "water"] },
  { name: "Atlantic Ocean Waters", flag: "🌊", category: "realm", keywords: ["ocean", "sea", "deep"] },
  { name: "Amazon Rainforest", flag: "🌿", category: "realm", keywords: ["jungle", "forest", "brazil"] },
  { name: "High Himalayas", flag: "🏔️", category: "realm", keywords: ["mountains", "everest", "snow"] },
  { name: "Faroe Islands (North Atlantic)", flag: "🌊", category: "realm", keywords: ["islands", "ocean", "cliffs"] },
  { name: "Sahara Desert Stargazing Camp", flag: "🏜️", category: "realm", keywords: ["desert", "dunes", "stars"] },
  { name: "Antarctica Research Base", flag: "❄️", category: "realm", keywords: ["polar", "ice", "south pole"] },
  { name: "Kyoto Temple Sanctuary", flag: "⛩️", category: "realm", keywords: ["japan", "peace", "zen"] },

  // World Countries (A-Z)
  { name: "Afghanistan", flag: "🇦🇫", category: "nation" },
  { name: "Albania", flag: "🇦🇱", category: "nation" },
  { name: "Algeria", flag: "🇩🇿", category: "nation" },
  { name: "Andorra", flag: "🇦🇩", category: "nation" },
  { name: "Angola", flag: "🇦🇴", category: "nation" },
  { name: "Antigua and Barbuda", flag: "🇦🇬", category: "nation" },
  { name: "Argentina", flag: "🇦🇷", category: "nation" },
  { name: "Armenia", flag: "🇦🇲", category: "nation" },
  { name: "Australia", flag: "🇦🇺", category: "nation" },
  { name: "Austria", flag: "🇦🇹", category: "nation" },
  { name: "Azerbaijan", flag: "🇦🇿", category: "nation" },
  { name: "Bahamas", flag: "🇧🇸", category: "nation" },
  { name: "Bahrain", flag: "🇧🇭", category: "nation" },
  { name: "Bangladesh", flag: "🇧🇩", category: "nation" },
  { name: "Barbados", flag: "🇧🇧", category: "nation" },
  { name: "Belarus", flag: "🇧🇾", category: "nation" },
  { name: "Belgium", flag: "🇧🇪", category: "nation" },
  { name: "Belize", flag: "🇧🇿", category: "nation" },
  { name: "Benin", flag: "🇧🇯", category: "nation" },
  { name: "Bhutan", flag: "🇧🇹", category: "nation" },
  { name: "Bolivia", flag: "🇧🇴", category: "nation" },
  { name: "Bosnia and Herzegovina", flag: "🇧🇦", category: "nation" },
  { name: "Botswana", flag: "🇧🇼", category: "nation" },
  { name: "Brazil", flag: "🇧🇷", category: "nation" },
  { name: "Brunei", flag: "🇧🇳", category: "nation" },
  { name: "Bulgaria", flag: "🇧🇬", category: "nation" },
  { name: "Burkina Faso", flag: "🇧🇫", category: "nation" },
  { name: "Burundi", flag: "🇧🇮", category: "nation" },
  { name: "Cabo Verde", flag: "🇨🇻", category: "nation" },
  { name: "Cambodia", flag: "🇰🇭", category: "nation" },
  { name: "Cameroon", flag: "🇨🇲", category: "nation" },
  { name: "Canada", flag: "🇨🇦", category: "nation" },
  { name: "Central African Republic", flag: "🇨🇫", category: "nation" },
  { name: "Chad", flag: "🇹🇩", category: "nation" },
  { name: "Chile", flag: "🇨🇱", category: "nation" },
  { name: "China", flag: "🇨🇳", category: "nation" },
  { name: "Colombia", flag: "🇨🇴", category: "nation" },
  { name: "Comoros", flag: "🇰🇲", category: "nation" },
  { name: "Congo (Congo-Brazzaville)", flag: "🇨🇬", category: "nation" },
  { name: "Costa Rica", flag: "🇨🇷", category: "nation" },
  { name: "Croatia", flag: "🇭🇷", category: "nation" },
  { name: "Cuba", flag: "🇨🇺", category: "nation" },
  { name: "Cyprus", flag: "🇨🇾", category: "nation" },
  { name: "Czech Republic", flag: "🇨🇿", category: "nation" },
  { name: "Democratic Republic of the Congo", flag: "🇨🇩", category: "nation" },
  { name: "Denmark", flag: "🇩🇰", category: "nation" },
  { name: "Djibouti", flag: "🇩🇯", category: "nation" },
  { name: "Dominica", flag: "🇩🇲", category: "nation" },
  { name: "Dominican Republic", flag: "🇩🇴", category: "nation" },
  { name: "Ecuador", flag: "🇪🇨", category: "nation" },
  { name: "Egypt", flag: "🇪🇬", category: "nation" },
  { name: "El Salvador", flag: "🇸🇻", category: "nation" },
  { name: "Equatorial Guinea", flag: "🇬🇶", category: "nation" },
  { name: "Eritrea", flag: "🇪🇷", category: "nation" },
  { name: "Estonia", flag: "🇪🇪", category: "nation" },
  { name: "Eswatini", flag: "🇸🇿", category: "nation" },
  { name: "Ethiopia", flag: "🇪🇹", category: "nation" },
  { name: "Fiji", flag: "🇫🇯", category: "nation" },
  { name: "Finland", flag: "🇫🇮", category: "nation" },
  { name: "France", flag: "🇫🇷", category: "nation" },
  { name: "Gabon", flag: "🇬🇦", category: "nation" },
  { name: "Gambia", flag: "🇬🇲", category: "nation" },
  { name: "Georgia", flag: "🇬🇪", category: "nation" },
  { name: "Germany", flag: "🇩🇪", category: "nation" },
  { name: "Ghana", flag: "🇬🇭", category: "nation" },
  { name: "Greece", flag: "🇬🇷", category: "nation" },
  { name: "Grenada", flag: "🇬🇩", category: "nation" },
  { name: "Guatemala", flag: "🇬🇹", category: "nation" },
  { name: "Guinea", flag: "🇬🇳", category: "nation" },
  { name: "Guinea-Bissau", flag: "🇬🇼", category: "nation" },
  { name: "Guyana", flag: "🇬🇾", category: "nation" },
  { name: "Haiti", flag: "🇭🇹", category: "nation" },
  { name: "Holy See (Vatican City)", flag: "🇻🇦", category: "nation" },
  { name: "Honduras", flag: "🇭🇳", category: "nation" },
  { name: "Hungary", flag: "🇭🇺", category: "nation" },
  { name: "Iceland", flag: "🇮🇸", category: "nation" },
  { name: "India", flag: "🇮🇳", category: "nation" },
  { name: "Indonesia", flag: "🇮🇩", category: "nation" },
  { name: "Iran", flag: "🇮🇷", category: "nation" },
  { name: "Iraq", flag: "🇮🇶", category: "nation" },
  { name: "Ireland", flag: "🇮🇪", category: "nation" },
  { name: "Israel", flag: "🇮🇱", category: "nation" },
  { name: "Italy", flag: "🇮🇹", category: "nation" },
  { name: "Jamaica", flag: "🇯🇲", category: "nation" },
  { name: "Japan", flag: "🇯🇵", category: "nation" },
  { name: "Jordan", flag: "🇯🇴", category: "nation" },
  { name: "Kazakhstan", flag: "🇰🇿", category: "nation" },
  { name: "Kenya", flag: "🇰🇪", category: "nation" },
  { name: "Kiribati", flag: "🇰🇮", category: "nation" },
  { name: "Kuwait", flag: "🇰🇼", category: "nation" },
  { name: "Kyrgyzstan", flag: "🇰🇬", category: "nation" },
  { name: "Laos", flag: "🇱🇦", category: "nation" },
  { name: "Latvia", flag: "🇱🇻", category: "nation" },
  { name: "Lebanon", flag: "🇱🇧", category: "nation" },
  { name: "Lesotho", flag: "🇱🇸", category: "nation" },
  { name: "Liberia", flag: "🇱🇷", category: "nation" },
  { name: "Libya", flag: "🇱🇾", category: "nation" },
  { name: "Liechtenstein", flag: "🇱🇮", category: "nation" },
  { name: "Lithuania", flag: "🇱🇹", category: "nation" },
  { name: "Luxembourg", flag: "🇱🇺", category: "nation" },
  { name: "Madagascar", flag: "🇲🇬", category: "nation" },
  { name: "Malawi", flag: "🇲🇼", category: "nation" },
  { name: "Malaysia", flag: "🇲🇾", category: "nation" },
  { name: "Maldives", flag: "🇲🇻", category: "nation" },
  { name: "Mali", flag: "🇲🇱", category: "nation" },
  { name: "Malta", flag: "🇲🇹", category: "nation" },
  { name: "Marshall Islands", flag: "🇲🇭", category: "nation" },
  { name: "Mauritania", flag: "🇲🇷", category: "nation" },
  { name: "Mauritius", flag: "🇲🇺", category: "nation" },
  { name: "Mexico", flag: "🇲🇽", category: "nation" },
  { name: "Micronesia", flag: "🇫🇲", category: "nation" },
  { name: "Moldova", flag: "🇲🇩", category: "nation" },
  { name: "Monaco", flag: "🇲🇨", category: "nation" },
  { name: "Mongolia", flag: "🇲🇳", category: "nation" },
  { name: "Montenegro", flag: "🇲🇪", category: "nation" },
  { name: "Morocco", flag: "🇲🇦", category: "nation" },
  { name: "Mozambique", flag: "🇲🇿", category: "nation" },
  { name: "Myanmar (Burma)", flag: "🇲🇲", category: "nation" },
  { name: "Namibia", flag: "🇳🇦", category: "nation" },
  { name: "Nauru", flag: "🇳🇷", category: "nation" },
  { name: "Nepal", flag: "🇳🇵", category: "nation" },
  { name: "Netherlands", flag: "🇳🇱", category: "nation" },
  { name: "New Zealand", flag: "🇳🇿", category: "nation" },
  { name: "Nicaragua", flag: "🇳🇮", category: "nation" },
  { name: "Niger", flag: "🇳🇪", category: "nation" },
  { name: "Nigeria", flag: "🇳🇬", category: "nation" },
  { name: "North Korea", flag: "🇰🇵", category: "nation" },
  { name: "North Macedonia", flag: "🇲🇰", category: "nation" },
  { name: "Norway", flag: "🇳🇴", category: "nation" },
  { name: "Oman", flag: "🇴🇲", category: "nation" },
  { name: "Pakistan", flag: "🇵🇰", category: "nation" },
  { name: "Palau", flag: "🇵🇼", category: "nation" },
  { name: "Palestine State", flag: "🇵🇸", category: "nation" },
  { name: "Panama", flag: "🇵🇦", category: "nation" },
  { name: "Papua New Guinea", flag: "🇵🇬", category: "nation" },
  { name: "Paraguay", flag: "🇵🇾", category: "nation" },
  { name: "Peru", flag: "🇵🇪", category: "nation" },
  { name: "Philippines", flag: "🇵🇭", category: "nation" },
  { name: "Poland", flag: "🇵🇱", category: "nation" },
  { name: "Portugal", flag: "🇵🇹", category: "nation" },
  { name: "Qatar", flag: "🇶🇦", category: "nation" },
  { name: "Romania", flag: "🇷🇴", category: "nation" },
  { name: "Russia", flag: "🇷🇺", category: "nation" },
  { name: "Rwanda", flag: "🇷🇼", category: "nation" },
  { name: "Saint Kitts and Nevis", flag: "🇰🇳", category: "nation" },
  { name: "Saint Lucia", flag: "🇱🇨", category: "nation" },
  { name: "Saint Vincent and the Grenadines", flag: "🇻🇨", category: "nation" },
  { name: "Samoa", flag: "🇼🇸", category: "nation" },
  { name: "San Marino", flag: "🇸🇲", category: "nation" },
  { name: "Sao Tome and Principe", flag: "🇸🇹", category: "nation" },
  { name: "Saudi Arabia", flag: "🇸🇦", category: "nation" },
  { name: "Senegal", flag: "🇸🇳", category: "nation" },
  { name: "Serbia", flag: "🇷🇸", category: "nation" },
  { name: "Seychelles", flag: "🇸🇨", category: "nation" },
  { name: "Sierra Leone", flag: "🇸🇱", category: "nation" },
  { name: "Singapore", flag: "🇸🇬", category: "nation" },
  { name: "Slovakia", flag: "🇸🇰", category: "nation" },
  { name: "Slovenia", flag: "🇸🇮", category: "nation" },
  { name: "Solomon Islands", flag: "🇸🇧", category: "nation" },
  { name: "Somalia", flag: "🇸🇴", category: "nation" },
  { name: "South Africa", flag: "🇿🇦", category: "nation" },
  { name: "South Korea", flag: "🇰🇷", category: "nation" },
  { name: "South Sudan", flag: "🇸🇸", category: "nation" },
  { name: "Spain", flag: "🇪🇸", category: "nation" },
  { name: "Sri Lanka", flag: "🇱🇰", category: "nation" },
  { name: "Sudan", flag: "🇸🇩", category: "nation" },
  { name: "Suriname", flag: "🇸🇷", category: "nation" },
  { name: "Sweden", flag: "🇸🇪", category: "nation" },
  { name: "Switzerland", flag: "🇨🇭", category: "nation" },
  { name: "Syria", flag: "🇸🇾", category: "nation" },
  { name: "Tajikistan", flag: "🇹🇯", category: "nation" },
  { name: "Tanzania", flag: "🇹🇿", category: "nation" },
  { name: "Thailand", flag: "🇹🇭", category: "nation" },
  { name: "Timor-Leste", flag: "🇹🇱", category: "nation" },
  { name: "Togo", flag: "🇹🇬", category: "nation" },
  { name: "Tonga", flag: "🇹🇴", category: "nation" },
  { name: "Trinidad and Tobago", flag: "🇹🇹", category: "nation" },
  { name: "Tunisia", flag: "🇹🇳", category: "nation" },
  { name: "Turkey", flag: "🇹🇷", category: "nation" },
  { name: "Turkmenistan", flag: "🇹🇲", category: "nation" },
  { name: "Tuvalu", flag: "🇹🇻", category: "nation" },
  { name: "Uganda", flag: "🇺🇬", category: "nation" },
  { name: "Ukraine", flag: "🇺🇦", category: "nation" },
  { name: "United Arab Emirates", flag: "🇦🇪", category: "nation" },
  { name: "United Kingdom", flag: "🇬🇧", category: "nation", keywords: ["england", "scotland", "wales", "london"] },
  { name: "United States", flag: "🇺🇸", category: "nation", keywords: ["usa", "america", "us", "new york", "california"] },
  { name: "Uruguay", flag: "🇺🇾", category: "nation" },
  { name: "Uzbekistan", flag: "🇺🇿", category: "nation" },
  { name: "Vanuatu", flag: "🇻🇺", category: "nation" },
  { name: "Venezuela", flag: "🇻🇪", category: "nation" },
  { name: "Vietnam", flag: "🇻🇳", category: "nation" },
  { name: "Yemen", flag: "🇾🇪", category: "nation" },
  { name: "Zambia", flag: "🇿🇲", category: "nation" },
  { name: "Zimbabwe", flag: "🇿🇼", category: "nation" },
];

export function filterRegions(query: string, maxResults: number = 10): EarthRegion[] {
  if (!query || !query.trim()) return [];
  const q = query.trim().toLowerCase();

  const scored = WORLD_REGIONS.map((region) => {
    const nameLower = region.name.toLowerCase();
    let score = 0;

    if (nameLower === q) {
      score = 100;
    } else if (nameLower.startsWith(q)) {
      score = 80;
    } else {
      const words = nameLower.split(/[\s,()]+/);
      if (words.some((w) => w.startsWith(q))) {
        score = 65;
      } else if (nameLower.includes(q)) {
        score = 50;
      } else if (region.keywords && region.keywords.some((k) => k.startsWith(q))) {
        score = 40;
      } else if (region.keywords && region.keywords.some((k) => k.includes(q))) {
        score = 30;
      }
    }

    return { region, score };
  })
    .filter((item) => item.score > 0)
    .sort((a, b) => b.score - a.score);

  return scored.slice(0, maxResults).map((item) => item.region);
}

